defmodule RecGPT.Repo.Migrations.DropCatalogItemXmpJsonldView do
  @moduledoc "Drops the catalog_item_xmp_jsonld view. XMP JSON-LD is generated by RecGPT.Xmp.Jsonld.from_catalog_item/1 from catalog_item rows."
  use Ecto.Migration

  def up do
    execute("DROP VIEW IF EXISTS catalog_item_xmp_jsonld")
  end

  def down do
    execute("""
    CREATE VIEW catalog_item_xmp_jsonld AS
    SELECT
      item_id,
      source_dataset,
      json_object(
        '@context', json_object('dc', 'http://purl.org/dc/elements/1.1/', 'dcterms', 'http://purl.org/dc/terms/'),
        'dc:title', dc_title,
        'dc:description', dc_description,
        'dc:identifier', source_dataset || ':' || item_id,
        'dcterms:source', dcterms_source
      ) AS item_xmp_jsonld
    FROM catalog_item
    """)
  end
end
