defmodule RecGPT.Repo.Migrations.CreateEtnfClickstream do
  @moduledoc "ETNF/BCNF catalog_item + event. XMP JSON-LD is generated by RecGPT.Xmp.Jsonld.from_catalog_item/1 from catalog_item."
  use Ecto.Migration

  def change do
    create table(:catalog_item, primary_key: false) do
      add :item_id, :integer, null: false, primary_key: true
      add :source_dataset, :string, null: false, primary_key: true
      add :dc_title, :string, null: false
      add :dc_description, :string, null: false
      add :dc_type, :string
      add :dcterms_source, :string, null: false
      timestamps(type: :utc_datetime_usec)
    end

    create table(:event, primary_key: false) do
      add :session_id, :integer, null: false, primary_key: true
      add :ord, :integer, null: false, primary_key: true
      add :item_id, :integer, null: false
      add :source_dataset, :string, null: false
      timestamps(type: :utc_datetime_usec)
    end

    create index(:event, [:session_id])
    create index(:event, [:session_id, :ord])
    create index(:event, [:item_id])
  end
end
